version: '2.0'

services:

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/opt/ditlog-webservice
    ports:
      - "8080"
      - "35729:35729"

volumes:
  app_build:
    driver: local
  app_out:
    driver: local
  oracle_data:
    driver: local

